before:
  hooks:
    - go mod tidy

builds:
  - id: frabit-server
    main: ./cmd/frabit-server
    binary: frabit-server
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/frabits/frabit/common/version.version={{ .Version }}
      - -X github.com/frabits/frabit/common/version.commit={{ .ShortCommit }}
      - -X github.com/frabits/frabit/common/version.buildDate={{ .CommitDate }}
  - id: frabit-agent
    main: ./agent
    binary: frabit-agent
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/frabits/frabit/pkg/common/version.version={{ .Version }}
      - -X github.com/frabits/frabit/common/pkg/version.commit={{ .ShortCommit }}
      - -X github.com/frabits/frabit/common/pkg/version.buildDate={{ .CommitDate }}
  - id: frabit-admin
    main: ./admin
    binary: frabit-admin
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/frabits/frabit/pkg/common/version.version={{ .Version }}
      - -X github.com/frabits/frabit/common/pkg/version.commit={{ .ShortCommit }}
      - -X github.com/frabits/frabit/common/pkg/version.buildDate={{ .CommitDate }}
archives:

nfpms:
  -
    id: frabit-server
    package_name: frabit-server
    file_name_template: "{{ .ConventionalFileName }}"
    builds:
      - frabit-admin
      - frabit-server
    vendor: Frabit Inc.

    homepage: https://github.com/frabits/frabit

    maintainer: Frabit Labs

    description: |-
      The next-gene database automatic platform

    license: GPLv3

    formats:
      - deb
      - rpm
    bindir: /usr/bin
 
    section: default
    rpm:
      # RPM specific scripts.
      scripts:
      summary: The next-gene database automatic platform
      group: Unspecified
      compression: lzma

    deb:
      scripts:
      triggers:
        interest:
          - some-trigger-name
        activate:
          - another-trigger-name
      breaks:
        - some-package

      signature:
        type: origin
  - id: frabit-agent
    package_name: frabit-agent
    file_name_template: "{{ .ConventionalFileName }}"
    builds:
      - frabit-agent
    vendor: Frabit Inc.
    homepage: https://github.com/frabits/frabit
    maintainer: Frabit Labs
    description: |-
      The next-gene database automatic platform
    license: GPLv3
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    section: default

    # Priority.
    priority: extra
    meta: true

    rpm:
      scripts:
      summary: The next-gene database automatic platform
      group: Database
      compression: lzma

    deb:
      scripts:
      triggers:
        interest:
          - some-trigger-name
        activate:
          - another-trigger-name
      breaks:
        - some-package
      signature:
        type: origin

brews:
  -
    name: frabit
    tap:
      owner: frabits
      name: homebrew-tap
    commit_author:
      name: goreleaser
      email: support@frabit.io
    folder: Formula
    homepage: https://www.frabit.tech
    description: "The next-gene database automatic platform"

checksum:
  name_template: 'checksum.txt'
snapshot:
  name_template: "{{ .Version }}"
release:
