before:
  hooks:
    - go mod tidy
builds:
  - id: frabit-server
    main: ./cmd/frabit-server
    binary: frabit-server
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

  - id: frabit-agent
    main: ./agent
    binary: frabit-agent
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

  - id: frabit-admin
    main: ./admin
    binary: frabit-admin
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:

nfpms:
  -
    id: frabit-server
    package_name: frabit-server

    # Default:`{{ .PackageName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}`
    file_name_template: "{{ .ConventionalFileName }}"
    builds:
      - frabit-admin
      - frabit-server
    vendor: Frabit Inc.

    homepage: https://github.com/frabits/frabit

    maintainer: Blylei <blylei.info@gmail.com>

    description: |-
      Drum rolls installer package.
      Software to create fast and easy drum rolls.

    license: GPLv3

    formats:
      - deb
      - rpm
    bindir: /usr/bin

    # epoch: 2

    # Section.
    section: default

    # Custom configuration applied only to the RPM packager.
    rpm:
      # RPM specific scripts.
      scripts:
        # The pretrans script runs before all RPM package transactions / stages.
        # pretrans: ./scripts/pretrans.sh
        # The posttrans script runs after all RPM package transactions / stages.
        # posttrans: ./scripts/posttrans.sh

      # The package summary. This is, by default, the first line of the
      # description, but can be explicitly provided here.
      # Defaults to the first line of the description.
      summary: Explicit Summary for Sample Package

      # The package group. This option is deprecated by most distros
      # but required by old distros like CentOS 5 / EL 5 and earlier.
      group: Unspecified
      compression: lzma

    deb:
      scripts:
        # Deb rules script.
        # rules: foo.sh
        # Deb templates file, when using debconf.
        # templates: templates
      triggers:
        # register interest on a trigger activated by another package
        # (also available: interest_await, interest_noawait)
        interest:
          - some-trigger-name
        # activate a trigger for another package
        # (also available: activate_await, activate_noawait)
        activate:
          - another-trigger-name

      # Packages which would break if this package would be installed.
      # The installation of this package is blocked if `some-package`
      # is already installed.
      breaks:
        - some-package

      # The package is signed if a key_file is set
      signature:
        # Template to the PGP secret key file path (can also be ASCII-armored).
        # The passphrase is taken from the environment variable
        # `$NFPM_ID_DEB_PASSPHRASE` with a fallback to `$NFPM_ID_PASSPHRASE`,
        # where ID is the id of the current nfpm config.
        # The id will be transformed to uppercase.
        # E.g. If your nfpm id is 'default' then the deb-specific passphrase
        # should be set as `$NFPM_DEFAULT_DEB_PASSPHRASE`
        # key_file: '{{ .Env.GPG_KEY_PATH }}'

        # The type describes the signers role, possible values are "origin",
        # "maint" and "archive". If unset, the type defaults to "origin".
        type: origin
  - id: frabit-agent
    package_name: frabit-agent
    file_name_template: "{{ .ConventionalFileName }}"
    builds:
      - frabit-agent
    vendor: Frabit Inc.
    homepage: https://github.com/frabits/frabit
    maintainer: Blylei <blylei.info@gmail.com>
    description: |-
      Drum rolls installer package.
      Software to create fast and easy drum rolls.
    license: GPLv3
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    # epoch: 2

    # Section.
    section: default

    # Priority.
    priority: extra
    meta: true

    rpm:
      scripts:
      # The pretrans script runs before all RPM package transactions / stages.
      # pretrans: ./scripts/pretrans.sh
      # The posttrans script runs after all RPM package transactions / stages.
      # posttrans: ./scripts/posttrans.sh

      # The package summary. This is, by default, the first line of the
      # description, but can be explicitly provided here.
      # Defaults to the first line of the description.
      summary: Explicit Summary for Sample Package
      group: Unspecified
      compression: lzma

    deb:
      scripts:
      # Deb rules script.
      # rules: foo.sh
      # Deb templates file, when using debconf.
      # templates: templates
      triggers:
        interest:
          - some-trigger-name
        # activate a trigger for another package
        # (also available: activate_await, activate_noawait)
        activate:
          - another-trigger-name
      breaks:
        - some-package

      # The package is signed if a key_file is set
      signature:
        # Template to the PGP secret key file path (can also be ASCII-armored).
        # The passphrase is taken from the environment variable
        # `$NFPM_ID_DEB_PASSPHRASE` with a fallback to `$NFPM_ID_PASSPHRASE`,
        # where ID is the id of the current nfpm config.
        # The id will be transformed to uppercase.
        # E.g. If your nfpm id is 'default' then the deb-specific passphrase
        # should be set as `$NFPM_DEFAULT_DEB_PASSPHRASE`
        # key_file: '{{ .Env.GPG_KEY_PATH }}'

        # The type describes the signers role, possible values are "origin",
        # "maint" and "archive". If unset, the type defaults to "origin".
        type: origin

checksum:
  name_template: 'checksum.txt'

snapshot:
  name_template: "{{ .Version }}"

release:
  prerelease: auto
