before:
  hooks:
    - go mod tidy

builds:
  - id: frabit-server
    main: ./cmd/frabit-server
    binary: frabit-server
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
  - id: frabit-agent
    main: ./agent
    binary: frabit-agent
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
  - id: frabit-admin
    main: ./admin
    binary: frabit-admin
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
archives:

nfpms:
  -
    id: frabit-server
    package_name: frabit-server
    file_name_template: "{{ .ConventionalFileName }}"
    builds:
      - frabit-admin
      - frabit-server
    vendor: Frabit Inc.

    homepage: https://github.com/frabits/frabit

    maintainer: Blylei <blylei.info@gmail.com>

    description: |-
      The next-generation database automatic operation platform.

    license: GPLv3

    formats:
      - deb
      - rpm
    bindir: /usr/bin

    # epoch: 2

    # Section.
    section: default
    rpm:
      # RPM specific scripts.
      scripts:
      summary: The next-generation database automatic operation platform
      group: Unspecified
      compression: lzma

    deb:
      scripts:
      triggers:
        interest:
          - some-trigger-name
        activate:
          - another-trigger-name
      breaks:
        - some-package

      signature:
        type: origin
  - id: frabit-agent
    package_name: frabit-agent
    file_name_template: "{{ .ConventionalFileName }}"
    builds:
      - frabit-agent
    vendor: Frabit Inc.
    homepage: https://github.com/frabits/frabit
    maintainer: Blylei <blylei.info@gmail.com>
    description: |-
      The next-generation database automatic operation platform
    license: GPLv3
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    section: default

    # Priority.
    priority: extra
    meta: true

    rpm:
      scripts:
      summary: The next-generation database automatic operation platform
      group: Database
      compression: lzma

    deb:
      scripts:
      triggers:
        interest:
          - some-trigger-name
        activate:
          - another-trigger-name
      breaks:
        - some-package
      signature:
        type: origin
brews:
  -
    name: frabit
    tap:
      owner: frabits
      name: homebrew-tap
    commit_author:
      name: goreleaser
      email: support@frabit.io
    folder: Formula
    homepage: https://www.frabit.tech/
    description: "The next-generation database automatic operation platform"


checksum:
  name_template: 'checksum.txt'
snapshot:
  name_template: "{{ .Version }}"
release:
