# This just for backend database to store metadata
db_info:
  host: "127.0.0.1"
  port: 3306
  user: "frabit"
  passwd: "Frabit_demo123"
  database : "frabit"

# The following config for Frabit backend
server:
  port: 9180
  debug: false
  plugin_dir: "/usr/local/frabit/plugins"
  log_file: "/var/log/frabit.log"