name: ci

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
  workflow_dispatch:

env:
  GOVERSION: "1.18"
jobs:
  test:
    name: Check code quality and run tests
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{env.GOVERSION}}

      - name: Report coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: go install github.com/mattn/goveralls && goveralls -v -coverprofile=coverage.out -service=github

  release:
    name: Build and deploy new release
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Set up latest Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.*

      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_GORELEASER_PAT }}

