name: release

on:
  push:
    branches:
      - 'main'
#    tags:
#      - 'v*'
  workflow_dispatch:
permissions:
  contents: write
env:
  GOVERSION: "1.18"
jobs:
  release:
    name: Build and publish new release
    runs-on: ubuntu-latest
    steps:
      - name: Set up latest Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.*

      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: npm
          cache-dependency-path: ""
          # cache-dependency-path: "frontend/package-lock.yaml"
      - run: npm install --frozen-lockfile
        working-directory: frontend
      - run: npm release
        working-directory: frontend

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}