name: release

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
  workflow_dispatch:
permissions:
  contents: write
env:
  GOVERSION: "1.18"
jobs:
  test:
    name: Check code quality and run tests
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{env.GOVERSION}}

  release:
    name: Build and deploy new release
    runs-on: ubuntu-latest
    steps:
      - name: Set up latest Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.*

      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}

